module: KituraMarkdown
author: IBM and the Kitura project authors
github_url: https://github.com/Kitura/Kitura-Markdown/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, KituraMarkdown.xcodeproj, -target, KituraMarkdown, LIBRARY_SEARCH_PATHS=.build/debug]

